# https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/languages/go/
# https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/test-coverage/test-execution-parameters/
# https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/importing-external-issues/external-analyzer-reports/
sonar.projectKey=luncliff-elftree
sonar.projectName=luncliff-elftree
sonar.projectVersion=0.2447.0

sonar.sources=.
sonar.exclusions=**/*_test.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

# sonar.go.tests.reportPaths=bin/test.out
# sonar.go.coverage.reportPaths=bin/cov.
