name: Go

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
        key: gocache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          gocache-${{ runner.os }}-
    - name: "Run go(build)"
      run: go build
    - name: "Run go(test)"
      run: go test
